[package]
name = "compiler"
version = "0.1.0"
authors = ["lucio"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cranelift = "0.59"
nom = "5"
anyhow = "1"